#!/bin/bash

python -m py5_tools.kernel.install --sys-prefix
python -m py5_tools.py5bot.install --sys-prefix

# python -m py5jupyter.kernels.py5.install --sys-prefix
# python -m py5jupyter.kernels.py5bot.install --sys-prefix
